version: '3.7'
services:
  sub-diy:
    build: .
    container_name: sub-diy
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 7700:80
      - 7701:25500
    volumes:
     - ./Subconverter.vue:/app/sub-web/src/views/Subconverter.vue:rw
     - ./nginx/logs:/var/log/nginx/:rw